// Многоезична поддръжка
let currentLanguage = 'bg';

const translations = {
    'bg': {
        'header_title': 'DayTech сервиз за компютри',
        'nav_home': 'Начало',
        'nav_services': 'Услуги',
        'nav_faq': 'Често задавани въпроси',
        'faq_title':'Често задавани въпроси',
        'faq_q1': 'Какви услуги предлагате?',
        'faq_a1': 'Ние предлагаме разнообразие от услуги като хардуерен ремонт, софтуерна инсталация, почистване на лаптопи и настолни компютри, инсталация на антивирус и други.',
        'faq_q2': 'Колко време отнема ремонтът?',
        'faq_a2': 'Зависи от услуга и сложността на проблема, но обикновено ремонтът отнема между 1 и 2 работни дни.',
        'faq_q3': 'Какви са цените на услугите?',
        'faq_a3': 'Цените на услугите се определят на база вида на ремонта. Можете да разгледате нашия ценоразпис за повече информация.',
        'faq_q4': 'Предлагате ли гаранция за услугите?',
        'faq_a4': 'Да, ние предлагаме гаранция за нашите ремонти в зависимост от типа услуга и ремонта.',
        'faq_q5': 'Как да подготвя компютъра си за ремонт?',
        'faq_a5': 'Препоръчваме ви да направите резервно копие на данните си, за да предотвратите загуба на информация по време на ремонта.',
        'faq_q6': 'Мога ли да запиша услуга онлайн?',
        'faq_a6': 'Да, можете да попълните нашия формуляр за поръчка на услуга на сайта и ще се свържем с вас за потвърждение.',
        'faq_q7': 'Как да се свържа с вас?',
        'faq_a7': 'Можете да се свържете с нас чрез формата за контакт на сайта или по телефон.',
        'faq_q8': 'Какво да правя, ако компютърът ми не се включва?',
        'faq_a8': 'Първо, проверете дали компютърът е включен към захранването. Ако не се включва, може да е проблем с захранващия блок или хардуера.',
        'faq_q9': 'Мога ли да се доверя на вашите ремонти?',
        'faq_a9': 'Да, ние сме професионалисти с дългогодишен опит и предлагаме качествени ремонти с гаранция.',
        'faq_q10': 'Предлагате ли услуги за бизнеса?',
        'faq_a10': 'Да, предлагаме специализирани услуги за малки и големи бизнеси, включително поддръжка на офис техника и мрежови решения.',
        'nav_about': 'За нас',
        'nav_contact': 'Контакти',
        'welcome_title': 'Добре дошли в нашия сервиз!',
        'welcome_text': '"Компютърът ви се държи странно? Не работи както трябва? В DayTech - вашият специализиран сервиз във Варна, имаме решението! Бързи, прецизни и достъпни ремонти на място - от забиващ софтуер до повреден хардуер. Обадете се сега или посетете нашия сервиз за повече информация!"',
        'services_title': 'Нашите услуги',
        'service1_title': 'Диагностика',
        'service1_desc': 'Преглед за развалени части, измерване на чипове и др.',
        'service1_full_desc': 'Преглед за развалени части, измерване на чипове и др. При отказ от ремонт – 40 лв.',
        'service2_title': 'Инсталация на ОС',
        'service2_desc': 'Инсталация на Windows/Linux със запазване на данните.',
        'service2_full_desc': 'Със запазване на данните и до 10 програми по избор.',
        'service3_title': 'Почистване',
        'service3_desc': 'Пълно почистване на лаптопи и настолни компютри.',
        'service3_full_desc': 'Включва смяна на термопаста, пълно разглобяване и почистване.',
        'service4_title': 'Инсталация на OpenOffice/LibreOffice',
        'service4_desc': 'Инсталация на безплатни офис пакети.',
        'service4_full_desc': 'Инсталация на OpenOffice или LibreOffice. Безплатни и мощни офис пакети, аналогични на MS Office.',
        'service5_title': 'Подмяна на RAM памет',
        'service5_desc': 'Подмяна на RAM памет на лаптоп.',
        'service5_full_desc': 'Подмяна на RAM памет с различни капацитети в зависимост от лаптопа.',
        'service6_title': 'Трансфер на данни',
        'service6_desc': 'Прехвърляне на данни от/на твърд диск.',
        'service6_full_desc': 'Прехвърляне на данни от/на твърд диск в зависимост от размера на данните.',
        'service7_title': 'Подмяна на матрица на лаптоп',
        'service7_desc': 'Замяна на екран на лаптоп.',
        'service7_full_desc': 'Подмяна на матрица на лаптоп с нова.',
        'service8_title': 'Подмяна на капак на лаптоп',
        'service8_desc': 'Подмяна на преден или заден капак.',
        'service8_full_desc': 'Подмяна на преден и заден капак на лаптопа с нови части.',
        'service9_title': 'Инсталация на антивирус',
        'service9_desc': 'Инсталация на антивирусна програма.',
        'service9_full_desc': 'Инсталация на антивирусна програма като Avast или предоставена от клиента.',
        'service10_title': 'Ремонт на дънна платка',
        'service10_desc': 'Ремонт на дънна платка на лаптоп.',
        'service10_full_desc': 'Ремонт на дънна платка чрез подмяна на компоненти с нови.',
        'service11_title': 'Флашване на BIOS',
        'service11_desc': 'Флашване на BIOS чипа.',
        'service11_full_desc': 'Флашване на BIOS чипа или прекодиране на BIOS с нова версия.',
        'service12_title': 'Преглед на захранване',
        'service12_desc': 'Проверка на захранващото устройство на компютър или лаптоп.',
        'service12_full_desc': 'Проверка на захранващото устройство за неработещи компоненти и диагностика.',
        'service13_title': 'Почистване на вентилатор',
        'service13_desc': 'Почистване на вентилатора за охлаждане на лаптоп или настолен компютър.',
        'service13_full_desc': 'Почистване на вентилатора за оптимизиране на охлаждането и намаляване на шума.',
        'service14_title': 'Премахване на вируси',
        'service14_desc': 'Премахване на вируси и зловреден софтуер от компютър.',
        'service14_full_desc': 'Премахване на вируси, зловреден софтуер и сканиране на системата за сигурност.',
        'service15_title': 'Ремонт на видео карта',
        'service15_desc': 'Ремонт на графична карта на настолен компютър или лаптоп.',
        'service15_full_desc': 'Ремонт на видео карта чрез подмяна на дефектни компоненти.',
        'service16_title': 'Зареждане на батерия',
        'service16_desc': 'Зареждане на батерия за лаптоп или мобилен компютър.',
        'service16_full_desc': 'Проверка и зареждане на лаптоп батерия.',
        'service17_title': 'Подмяна на SSD',
        'service17_desc': 'Подмяна на SSD диск в лаптоп.',
        'service17_full_desc': 'Подмяна на SSD диск за по-бърза работа на компютъра.',
        'service18_title': 'Оптимизация на системата',
        'service18_desc': 'Оптимизация на операционната система и ускоряване на компютъра.',
        'service18_full_desc': 'Оптимизация на системни процеси, изчистване на ненужни файлове и настройка на производителността.',
        'service19_title': 'Преглед на мрежова свързаност',
        'service19_desc': 'Проверка на мрежови настройки и свързаност.',
        'service19_full_desc': 'Проверка и диагностика на проблеми с интернет свързаност и мрежови настройки.',
        'service20_title': 'Ремонт на лаптопи след падане',
        'service20_desc': 'Ремонт на лаптопи след физическо увреждане или падане.',
        'service20_full_desc': 'Ремонт на лаптопи след падане, включително проверка на вътрешните компоненти за повреди.',
        'prices_title': 'Ценоразпис и услуги',
        'price_column': 'Цена',
        'service_column': 'Услуга',
        'description_column': 'Описание',
        'about_title': 'Кои сме ние',
        'about_text1': 'DayTech е вече над 5 години на българския пазар.',
        'about_text2': 'Ние предоставяме качествени ремонти на компютри и лаптопи, профилактика, диагностика и консултации.',
        "our_mission": "Нашата мисия",
        "mission_text": "Целта ни е да осигурим на клиентите си професионални, бързи и ефективни ремонти, като същевременно предлагаме достъпни цени и гарантирана качество. Ние разбираме важността на компютърната техника в ежедневието и бизнеса и се стараем да предлагаме решения, които да отговорят на всички ваши нужди.",
        "our_values": "Нашите ценности",
        "values_text": "Нашите основни ценности включват:",
        "values_professionalism": "Професионализъм: Специализиран екип с дългогодишен опит.",
        "values_honesty": "Честност: Изцяло прозрачни в услугите и цените си.",
        "values_reliability": "Надеждност: Доверие, което градим с всеки успешно завършен проект.",
        "values_customer_service": "Обслужване на клиента: Ние поставяме на първо място нуждите на нашите клиенти.",
        "our_team": "Нашият екип",
        "team_description": "Нашият екип от експерти в различни области на информационните технологии е готов да ви предложи индивидуални решения, които да отговорят на всички ваши изисквания. Вярваме, че всяка техника е уникална и заслужава внимание, което да гарантира дълготрайна и стабилна работа.",
        "our_vision": "Нашето виждане за бъдещето",
        "future_vision_description": "В бъдеще се стремим да разширим нашите услуги и да въведем иновации, които ще направят работата с компютърната техника още по-удобна и ефективна за нашите клиенти. Стремим се към непрекъснато подобряване на нашите технологии и процеси, за да предлагаме само най-доброто.",
        'contact_title': 'Свържете се с нас',
        'contact_text': 'Можете да ни пишете или да ни посетите в нашия офис в Варна.',
        'email_label': 'Имейл',
        'phone_label': 'Телефон',
        'address_label': 'Адрес',
        'address_text': 'ул. "Студентска" №4, Варна',
        'hours_label': 'Работно време',
        'hours_text': 'Понеделник-Петък: 10:00-20:00',
        'footer_contacts': 'Контакти: DayTechservices@gmail.com | тел: 089 123 4567',
        'form_title': 'Поръчай услуга',
        'form_name': 'Име',
        'form_email': 'Имейл',
        'form_service': 'Услуга',
        'form_message': 'Съобщение',
        'form_submit': 'Изпрати'

    },
    'en': {
        'header_title': 'DayTech Computer Service',
        'nav_home': 'Home',
        'nav_services': 'Services',
        'nav_faq': 'Frequently asked questions',
        'faq_title':'Frequently asked questions',
        'faq_q1': 'What services do you offer?',
        'faq_a1': 'We offer a variety of services such as hardware repair, software installation, cleaning of laptops and desktop computers, antivirus installation, and more.',
        'faq_q2': 'How long does a repair take?',
        'faq_a2': 'It depends on the service and the complexity of the issue, but usually, a repair takes between 1 and 2 business days.',
        'faq_q3': 'What are the prices for services?',
        'faq_a3': 'The prices of services are based on the type of repair. You can view our price list for more information.',
        'faq_q4': 'Do you offer a warranty on services?',
        'faq_a4': 'Yes, we offer a warranty on our repairs depending on the type of service and repair.',
        'faq_q5': 'How should I prepare my computer for repair?',
        'faq_a5': 'We recommend backing up your data to avoid any loss of information during the repair process.',
        'faq_q6': 'Can I book a service online?',
        'faq_a6': 'Yes, you can fill out our service order form on the website and we will contact you for confirmation.',
        'faq_q7': 'How can I contact you?',
        'faq_a7': 'You can contact us through the contact form on the website or by phone.',
        'faq_q8': 'What should I do if my computer won\'t turn on?',
        'faq_a8': 'First, check if the computer is connected to a power source. If it doesn’t turn on, there may be an issue with the power supply or hardware.',
        'faq_q9': 'Can I trust your repairs?',
        'faq_a9': 'Yes, we are professionals with years of experience and we offer quality repairs with a warranty.',
        'faq_q10': 'Do you offer services for businesses?',
        'faq_a10': 'Yes, we offer specialized services for small and large businesses, including office equipment maintenance and network solutions.',
        'nav_about': 'About Us',
        'nav_contact': 'Contact',
        'welcome_title': 'Welcome to our service!',
        'welcome_text': '"Is your computer behaving strangely? Not working as it should? At DayTech - your specialized service in Varna, we have the solution! Fast, precise, and affordable repairs on-site – from freezing software to damaged hardware. Call now or visit our service center for more information!"',
        'services_title': 'Our Services',
        'service1_title': 'Diagnostics',
        'service1_desc': 'Checking for faulty parts, chip measurements, etc.',
        'service1_full_desc': 'Checking for faulty parts, chip measurements, etc. If repair is refused - 40 BGN.',
        'service2_title': 'OS Installation',
        'service2_desc': 'Windows/Linux installation with data preservation.',
        'service2_full_desc': 'With data preservation and up to 10 programs of your choice.',
        'service3_title': 'Cleaning',
        'service3_desc': 'Full cleaning of laptops and desktop computers.',
        'service3_full_desc': 'Includes thermal paste replacement, full disassembly and cleaning.',
        'service4_title': 'OpenOffice/LibreOffice Installation',
        'service4_desc': 'Installation of free office suites.',
        'service4_full_desc': 'Installation of OpenOffice or LibreOffice. Free and powerful office suites similar to MS Office.',
        'service5_title': 'RAM Upgrade',
        'service5_desc': 'Upgrade of laptop RAM.',
        'service5_full_desc': 'Upgrading the RAM with different capacities depending on the laptop.',
        'service6_title': 'Data Transfer',
        'service6_desc': 'Transfer of data from/to hard drive.',
        'service6_full_desc': 'Transfer of data from/to hard drive depending on the size of the data.',
        'service7_title': 'Laptop Screen Replacement',
        'service7_desc': 'Replacing the laptop screen.',
        'service7_full_desc': 'Replacing the laptop screen with a new one.',
        'service8_title': 'Laptop Cover Replacement',
        'service8_desc': 'Replacement of front or back cover.',
        'service8_full_desc': 'Replacing the front and back covers of the laptop with new parts.',
        'service9_title': 'Antivirus Installation',
        'service9_desc': 'Installation of antivirus software.',
        'service9_full_desc': 'Installing antivirus software like Avast or provided by the client.',
        'service10_title': 'Motherboard Repair',
        'service10_desc': 'Repair of laptop motherboard.',
        'service10_full_desc': 'Repair of motherboard by replacing faulty components with new ones.',
        'service11_title': 'BIOS Flashing',
        'service11_desc': 'Flashing the BIOS chip.',
        'service11_full_desc': 'Flashing the BIOS chip or reprogramming the BIOS with a new version.',
        'service12_title': 'Power Supply Check',
        'service12_desc': 'Checking the power supply unit of a computer or laptop.',
        'service12_full_desc': 'Checking the power supply unit for faulty components and diagnostics.',
        'service13_title': 'Fan Cleaning',
        'service13_desc': 'Cleaning of the cooling fan in laptops and desktop computers.',
        'service13_full_desc': 'Cleaning of the cooling fan to optimize cooling and reduce noise.',
        'service14_title': 'Virus Removal',
        'service14_desc': 'Removal of viruses and malware from computers.',
        'service14_full_desc': 'Removal of viruses, malware and scanning the system for security.',
        'service15_title': 'Graphics Card Repair',
        'service15_desc': 'Repair of the graphics card in desktop or laptop computers.',
        'service15_full_desc': 'Repair of the graphics card by replacing faulty components.',
        'service16_title': 'Battery Charging',
        'service16_desc': 'Charging laptop or mobile computer battery.',
        'service16_full_desc': 'Checking and charging laptop battery.',
        'service17_title': 'SSD Upgrade',
        'service17_desc': 'Upgrading SSD in a laptop.',
        'service17_full_desc': 'Replacing the SSD for faster computer performance.',
        'service18_title': 'System Optimization',
        'service18_desc': 'Optimizing the operating system and speeding up the computer.',
        'service18_full_desc': 'Optimizing system processes, clearing unnecessary files, and tuning performance.',
        'service19_title': 'Network Connectivity Check',
        'service19_desc': 'Checking network settings and connectivity.',
        'service19_full_desc': 'Checking and diagnosing network and internet connection issues.',
        'service20_title': 'Laptop Repair After Drop',
        'service20_desc': 'Repair of laptops after physical damage or drop.',
        'service20_full_desc': 'Repairing laptops after a fall, including checking internal components for damage.',
        'prices_title': 'Price List and Services',
        'price_column': 'Price',
        'service_column': 'Service',
        'description_column': 'Description',
        'about_title': 'About Us',
        'about_text1': 'DayTech has been on the Bulgarian market for over 5 years.',
        'about_text2': 'We provide quality repairs of computers and laptops, maintenance, diagnostics and consultations.',
        "our_mission": "Our Mission",
        "mission_text": "Our goal is to provide our clients with professional, fast, and efficient repairs while offering affordable prices and guaranteed quality. We understand the importance of computer technology in everyday life and business, and we strive to offer solutions that meet all your needs.",
        "our_values": "Our Values",
        "values_text": "Our core values include:",
        "values_professionalism": "Professionalism: A specialized team with years of experience.",
        "values_honesty": "Honesty: Fully transparent with our services and pricing.",
        "values_reliability": "Reliability: Trust we build with each successfully completed project.",
        "values_customer_service": "Customer Service: We put our clients' needs first.",
        "our_team": "Our Team",
        "team_description": "Our team of experts in various fields of information technology is ready to offer personalized solutions that meet all your requirements. We believe that every piece of equipment is unique and deserves the attention that ensures long-lasting and stable operation.",
        "our_vision": "Our Vision for the Future",
        "future_vision_description": "In the future, we aim to expand our services and introduce innovations that will make working with computer technology even more convenient and effective for our clients. We are committed to continuously improving our technologies and processes to offer only the best.",
        'contact_title': 'Contact Us',
        'contact_text': 'You can write to us or visit our office in Varna.',
        'email_label': 'Email',
        'phone_label': 'Phone',
        'address_label': 'Address',
        'address_text': '4 "Studentska" Str., Varna',
        'hours_label': 'Working Hours',
        'hours_text': 'Monday-Friday: 10:00 AM - 8:00 PM',
        'footer_contacts': 'Contacts: DayTechservices@gmail.com | phone: 089 123 4567',
        'form_title': 'Order a Service',
        'form_name': 'Name',
        'form_email': 'Email',
        'form_service': 'Service',
        'form_message': 'Message',
        'form_submit': 'Submit'

    }
};


function setLanguage(lang) {
    currentLanguage = lang;
    document.documentElement.lang = lang;
    
    // Запазване на избрания език в localStorage
    localStorage.setItem('language', lang);
    
    // Промяна на активния бутон
    document.querySelectorAll('.language-switcher button').forEach(btn => {
        btn.classList.remove('active');
    });
    document.getElementById(`lang-${lang}`).classList.add('active');
    
    // Промяна на текстовете
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
}

// Инициализация при зареждане на страницата
document.addEventListener('DOMContentLoaded', function() {
    // Проверка за запазен език или използване на езика по подразбиране
    const savedLang = localStorage.getItem('language') || 'bg';
    setLanguage(savedLang);
    
    // Слушатели за бутоните за смяна на езика
    document.getElementById('lang-bg')?.addEventListener('click', () => setLanguage('bg'));
    document.getElementById('lang-en')?.addEventListener('click', () => setLanguage('en'));
    
});
